// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/svelte'

import _dashboard_finance from './dashboard-finance.bones.json'
import _dashboard_notes from './dashboard-notes.bones.json'
import _files_list from './files-list.bones.json'
import _finance_summary from './finance-summary.bones.json'
import _finance_transactions from './finance-transactions.bones.json'
import _note_card from './note-card.bones.json'
import _note_detail from './note-detail.bones.json'
import _route_content from './route-content.bones.json'
import _route_tool from './route-tool.bones.json'
import _tag_grid from './tag-grid.bones.json'

registerBones({
  "dashboard-finance": _dashboard_finance,
  "dashboard-notes": _dashboard_notes,
  "files-list": _files_list,
  "finance-summary": _finance_summary,
  "finance-transactions": _finance_transactions,
  "note-card": _note_card,
  "note-detail": _note_detail,
  "route-content": _route_content,
  "route-tool": _route_tool,
  "tag-grid": _tag_grid,
})
